// Generated by psc-bundle 0.7.0.0
var PS = { };
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff

  exports.returnE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  //- Semiring -------------------------------------------------------------------

  exports.intAdd = function (x) {
    return function (y) {
      /* jshint bitwise: false */
      return x + y | 0;
    };
  };

  exports.intMul = function (x) {
    return function (y) {
      /* jshint bitwise: false */
      return x * y | 0;
    };
  };

  //- Show -----------------------------------------------------------------------

  exports.showIntImpl = function (n) {
    return n.toString();
  };

  exports.showNumberImpl = function (n) {
    /* jshint bitwise: false */
    return n === (n | 0) ? n + ".0" : n.toString();
  };
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Prelude"];
  var Semigroupoid = function (compose) {
      this.compose = compose;
  };
  var Functor = function (map) {
      this.map = map;
  };
  var Apply = function (__superclass_Prelude$dotFunctor_0, apply) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.apply = apply;
  };
  var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.pure = pure;
  };
  var Bind = function (__superclass_Prelude$dotApply_0, bind) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.bind = bind;
  };
  var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
      this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
  };
  var Semiring = function (add, mul, one, zero) {
      this.add = add;
      this.mul = mul;
      this.one = one;
      this.zero = zero;
  };
  var Show = function (show) {
      this.show = show;
  };
  var zero = function (dict) {
      return dict.zero;
  };                                                                           
  var unit = {};
  var showNumber = new Show($foreign.showNumberImpl);
  var showInt = new Show($foreign.showIntImpl);
  var show = function (dict) {
      return dict.show;
  };                                                                            
  var semiringInt = new Semiring($foreign.intAdd, $foreign.intMul, 1, 0);
  var semigroupoidFn = new Semigroupoid(function (f) {
      return function (g) {
          return function (x) {
              return f(g(x));
          };
      };
  });                 
  var pure = function (dict) {
      return dict.pure;
  };
  var $$return = function (__dict_Applicative_2) {
      return pure(__dict_Applicative_2);
  };                   
  var one = function (dict) {
      return dict.one;
  };
  var mul = function (dict) {
      return dict.mul;
  };
  var map = function (dict) {
      return dict.map;
  };
  var $less$dollar$greater = function (__dict_Functor_5) {
      return map(__dict_Functor_5);
  };
  var compose = function (dict) {
      return dict.compose;
  };
  var functorFn = new Functor(compose(semigroupoidFn));
  var bind = function (dict) {
      return dict.bind;
  };
  var $greater$greater$eq = function (__dict_Bind_24) {
      return bind(__dict_Bind_24);
  }; 
  var apply = function (dict) {
      return dict.apply;
  };
  var $less$times$greater = function (__dict_Apply_25) {
      return apply(__dict_Apply_25);
  };
  var liftA1 = function (__dict_Applicative_26) {
      return function (f) {
          return function (a) {
              return $less$times$greater(__dict_Applicative_26["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_26)(f))(a);
          };
      };
  };
  var ap = function (__dict_Monad_30) {
      return function (f) {
          return function (a) {
              return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(f)(function (_5) {
                  return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(a)(function (_4) {
                      return $$return(__dict_Monad_30["__superclass_Prelude.Applicative_0"]())(_5(_4));
                  });
              });
          };
      };
  }; 
  var add = function (dict) {
      return dict.add;
  };
  var $plus = function (__dict_Semiring_31) {
      return add(__dict_Semiring_31);
  };
  exports["Show"] = Show;
  exports["Semiring"] = Semiring;
  exports["Monad"] = Monad;
  exports["Bind"] = Bind;
  exports["Applicative"] = Applicative;
  exports["Apply"] = Apply;
  exports["Functor"] = Functor;
  exports["Semigroupoid"] = Semigroupoid;
  exports["show"] = show;
  exports["+"] = $plus;
  exports["one"] = one;
  exports["mul"] = mul;
  exports["zero"] = zero;
  exports["add"] = add;
  exports["ap"] = ap;
  exports["return"] = $$return;
  exports[">>="] = $greater$greater$eq;
  exports["bind"] = bind;
  exports["liftA1"] = liftA1;
  exports["pure"] = pure;
  exports["apply"] = apply;
  exports["<$>"] = $less$dollar$greater;
  exports["map"] = map;
  exports["compose"] = compose;
  exports["unit"] = unit;
  exports["semigroupoidFn"] = semigroupoidFn;
  exports["functorFn"] = functorFn;
  exports["semiringInt"] = semiringInt;
  exports["showInt"] = showInt;
  exports["showNumber"] = showNumber;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];     
  var monadEff = new Prelude.Monad(function () {
      return applicativeEff;
  }, function () {
      return bindEff;
  });
  var bindEff = new Prelude.Bind(function () {
      return applyEff;
  }, $foreign.bindE);
  var applyEff = new Prelude.Apply(function () {
      return functorEff;
  }, Prelude.ap(monadEff));
  var applicativeEff = new Prelude.Applicative(function () {
      return applyEff;
  }, $foreign.returnE);
  var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
  exports["functorEff"] = functorEff;
  exports["applyEff"] = applyEff;
  exports["applicativeEff"] = applicativeEff;
  exports["bindEff"] = bindEff;
  exports["monadEff"] = monadEff;;
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports, console */
  "use strict";

  // module Control.Monad.Eff.Console

  exports.log = function (s) {
    return function () {
      console.log(s);
      return {};
    };
  };
 
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff.Console"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  exports["log"] = $foreign.log;;
 
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  /* global exports, window */
  "use strict";

  // module DOM.HTML

  exports.window = function () {
    return window;
  };
 
})(PS["DOM.HTML"] = PS["DOM.HTML"] || {});
(function(exports) {
  "use strict";

  // module Unsafe.Coerce

  exports.unsafeCoerce = function(x) { return x; }
 
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Unsafe.Coerce"];
  exports["unsafeCoerce"] = $foreign.unsafeCoerce;;
 
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["DOM.HTML.Types"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];
  var Data_Foreign = PS["Data.Foreign"];
  var Prelude = PS["Prelude"];
  var Data_Either = PS["Data.Either"];
  var Data_Foreign_Class = PS["Data.Foreign.Class"];
  var DOM_Event_Types = PS["DOM.Event.Types"];
  var DOM_Node_Types = PS["DOM.Node.Types"];                
  var htmlElementToElement = Unsafe_Coerce.unsafeCoerce;
  exports["htmlElementToElement"] = htmlElementToElement;;
 
})(PS["DOM.HTML.Types"] = PS["DOM.HTML.Types"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["DOM.HTML"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  exports["window"] = $foreign.window;;
 
})(PS["DOM.HTML"] = PS["DOM.HTML"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module DOM.HTML.Document

  exports.body = function (doc) {
    return function () {
      return doc.body;
    };
  };
 
})(PS["DOM.HTML.Document"] = PS["DOM.HTML.Document"] || {});
(function(exports) {
  /* global exports */
  "use strict";          

  exports.nullable = function(a, r, f) {
      return a == null ? r : f(a);
  }; 
 
})(PS["Data.Nullable"] = PS["Data.Nullable"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Extend = PS["Control.Extend"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Monoid = PS["Data.Monoid"];     
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;;
 
})(PS["Data.Maybe"] = PS["Data.Maybe"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Data.Nullable"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Function = PS["Data.Function"];
  var Prelude = PS["Prelude"];                                          
  var toMaybe = function (n) {
      return $foreign.nullable(n, Data_Maybe.Nothing.value, Data_Maybe.Just.create);
  };
  exports["toMaybe"] = toMaybe;;
 
})(PS["Data.Nullable"] = PS["Data.Nullable"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["DOM.HTML.Document"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_Nullable = PS["Data.Nullable"];
  var DOM = PS["DOM"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  exports["body"] = $foreign.body;;
 
})(PS["DOM.HTML.Document"] = PS["DOM.HTML.Document"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module DOM.HTML.Window

  exports.document = function (window) {
    return function () {
      return window.document;
    };
  };
 
})(PS["DOM.HTML.Window"] = PS["DOM.HTML.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["DOM.HTML.Window"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  exports["document"] = $foreign.document;;
 
})(PS["DOM.HTML.Window"] = PS["DOM.HTML.Window"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Maybe.Unsafe

  exports.unsafeThrow = function (msg) {
    throw new Error(msg);
  };
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Data.Maybe.Unsafe"];
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];     
  var fromJust = function (_226) {
      if (_226 instanceof Data_Maybe.Just) {
          return _226.value0;
      };
      if (_226 instanceof Data_Maybe.Nothing) {
          return $foreign.unsafeThrow("Data.Maybe.Unsafe.fromJust called on Nothing");
      };
      throw new Error("Failed pattern match at /home/travis/build/lewurm/geocaching-history/front-end/bower_components/purescript-maybe/src/Data/Maybe/Unsafe.purs line 10, column 1 - line 11, column 1: " + [ _226.constructor.name ]);
  };
  exports["fromJust"] = fromJust;;
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  "use strict";

  // module Leaflet.Icon

  exports.icon = function(opts) { return function() { return L.icon(opts); } }
 
})(PS["Leaflet.Icon"] = PS["Leaflet.Icon"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var Control_Monad_Eff = PS["Control.Monad.Eff"];     
  var Layer = function (addTo, toILayer) {
      this.addTo = addTo;
      this.toILayer = toILayer;
  };
  var toILayer = function (dict) {
      return dict.toILayer;
  };
  var addTo = function (dict) {
      return dict.addTo;
  };
  exports["Layer"] = Layer;
  exports["addTo"] = addTo;
  exports["toILayer"] = toILayer;;
 
})(PS["Leaflet.Types"] = PS["Leaflet.Types"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Leaflet.Icon"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Leaflet_Types = PS["Leaflet.Types"];
  exports["icon"] = $foreign.icon;;
 
})(PS["Leaflet.Icon"] = PS["Leaflet.Icon"] || {});
(function(exports) {
  "use strict";

  // module Leaflet.LatLng

  exports.latLng = function(n0) {
      return function(n1) {
          return L.latLng([n0,n1]);
      }
  }

 
})(PS["Leaflet.LatLng"] = PS["Leaflet.LatLng"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Leaflet.LatLng"];
  var Leaflet_Types = PS["Leaflet.Types"];
  exports["latLng"] = $foreign.latLng;;
 
})(PS["Leaflet.LatLng"] = PS["Leaflet.LatLng"] || {});
(function(exports) {
  "use strict";

  // module Leaflet.LatLngBounds

  exports.latLngBounds = function(l0) {
      return function(l1) {
          return L.latLngBounds([l0,l1]);
      }
  }
 
})(PS["Leaflet.LatLngBounds"] = PS["Leaflet.LatLngBounds"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Leaflet.LatLngBounds"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Leaflet_Types = PS["Leaflet.Types"];
  exports["latLngBounds"] = $foreign.latLngBounds;;
 
})(PS["Leaflet.LatLngBounds"] = PS["Leaflet.LatLngBounds"] || {});
(function(exports) {
  "use strict";

  // module Leaflet.Map

  exports.createMap = function(i) {
      return function(o) {
          return function() {
              return L.map(i,o);
          }
      }
  }
 
})(PS["Leaflet.Map"] = PS["Leaflet.Map"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Leaflet.Map"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Leaflet_Types = PS["Leaflet.Types"];
  exports["createMap"] = $foreign.createMap;;
 
})(PS["Leaflet.Map"] = PS["Leaflet.Map"] || {});
(function(exports) {
  "use strict";

  // module Leaflet.Marker

  exports.markerToILayer = function (l) { return l; }

  exports.addMarkerToMap = function (l) {
      return function(m) {
          return function() {
              return l.addTo(m);
          }
      }
  }

  exports.marker = function (o) {
      return function(l) {
          return L.marker(l,o);
      }
  }
 
})(PS["Leaflet.Marker"] = PS["Leaflet.Marker"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Leaflet.Marker"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Leaflet_Types = PS["Leaflet.Types"];     
  var markerLayer = new Leaflet_Types.Layer($foreign.addMarkerToMap, $foreign.markerToILayer);
  exports["markerLayer"] = markerLayer;
  exports["marker"] = $foreign.marker;;
 
})(PS["Leaflet.Marker"] = PS["Leaflet.Marker"] || {});
(function(exports) {
  "use strict";

  // module Leaflet.TileLayer

  exports.tileLayerToILayer = function(l) { return l; }

  exports.addTileLayerToMap = function(l) {
      return function(m) {
          return function() {
              return l.addTo(m);
          }
      }
  }

  exports.tileLayer = function(u) {
      return function(o) {
          return function() {
              return L.tileLayer(u,o);
          }
      }
  }
 
})(PS["Leaflet.TileLayer"] = PS["Leaflet.TileLayer"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["Leaflet.TileLayer"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Leaflet_Types = PS["Leaflet.Types"];     
  var tileLayerLayer = new Leaflet_Types.Layer($foreign.addTileLayerToMap, $foreign.tileLayerToILayer);
  exports["tileLayerLayer"] = tileLayerLayer;
  exports["tileLayer"] = $foreign.tileLayer;;
 
})(PS["Leaflet.TileLayer"] = PS["Leaflet.TileLayer"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module React.DOM

  function mkProps(props) {
      var result = {};

      for (var i = 0, len = props.length; i < len; i++) {
          var prop = props[i];

          for (var key in prop) {
              if (prop.hasOwnProperty(key)) {
                  result[key] = prop[key];
              }
          }
      }

      return result;
  };

  exports.mkDOM = function(tagName) {
      return function(props) {
          return function(children) {
              return React.createElement(tagName, props.length > 0 ? mkProps(props) : null, children);
          }
      }
  };

  exports.text = function(text) {
      return text;
  };
 
})(PS["React.DOM"] = PS["React.DOM"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports.writeState = function(ctx) {
      return function(state) {
          return function() {
              ctx.replaceState({
                  state: state
              });
              return function() {
                  return state;
              }
          };
      };
  };

  exports.readState = function(ctx) {
      return function() {
          return ctx.state.state;
      };
  };

  exports.createClass = function(ss) {
      var result = {};
      for (var s in ss) {
          if (ss.hasOwnProperty(s)) {
            if (s === "displayName") {
              result[s] = ss[s];
            }
            else if (s === "componentWillReceiveProps") {
              result[s] = (function(impl) {
                  return function(nextProps) {
                      return impl(this)(nextProps)();
                  }
              })(ss[s]);
            }
            else if (s === "shouldComponentUpdate") {
              result[s] = (function(impl) {
                  return function(nextProps, nextState) {
                      return impl(this)(nextProps)(nextState.state)();
                  }
              })(ss[s]);
            }
            else if (s === "componentWillUpdate") {
              result[s] = (function(impl) {
                  return function(nextProps, nextState) {
                      return impl(this)(nextProps)(nextState.state)();
                  }
              })(ss[s]);
            }
            else if (s === "componentDidUpdate") {
              result[s] = (function(impl) {
                  return function(prevProps, prevState) {
                      return impl(this)(prevProps)(prevState.state)();
                  }
              })(ss[s]);
            }
            else {
              result[s] = (function(impl) {
                  return function() {
                      return impl(this)();
                  }
              })(ss[s]);
            }
          }
      }
      result.getInitialState = function() {
          return {
              state: ss.getInitialState(this)()
          };
      };
      return React.createClass(result);
  };

  exports.handle = function(f) {
      return function(e) {
          return f(e)();
      };
  };

  exports.createFactory = function(clazz) {
    return React.createFactory(clazz);
  };

  exports.render = function(element) {
    return function(container) {
      return function() {
        return React.render(element, container);
      }
    };
  };                                            
 
})(PS["React"] = PS["React"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["React"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var spec = function (st) {
      return function (renderFn) {
          return {
              render: renderFn, 
              displayName: "", 
              getInitialState: function (_362) {
                  return Prelude.pure(Control_Monad_Eff.applicativeEff)(st);
              }, 
              componentWillMount: function (_363) {
                  return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
              }, 
              componentDidMount: function (_364) {
                  return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
              }, 
              componentWillReceiveProps: function (_366) {
                  return function (_365) {
                      return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
                  };
              }, 
              shouldComponentUpdate: function (_369) {
                  return function (_368) {
                      return function (_367) {
                          return Prelude["return"](Control_Monad_Eff.applicativeEff)(true);
                      };
                  };
              }, 
              componentWillUpdate: function (_372) {
                  return function (_371) {
                      return function (_370) {
                          return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
                      };
                  };
              }, 
              componentDidUpdate: function (_375) {
                  return function (_374) {
                      return function (_373) {
                          return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
                      };
                  };
              }, 
              componentWillUnmount: function (_376) {
                  return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
              }
          };
      };
  };
  exports["spec"] = spec;
  exports["render"] = $foreign.render;
  exports["createFactory"] = $foreign.createFactory;
  exports["createClass"] = $foreign.createClass;
  exports["handle"] = $foreign.handle;
  exports["writeState"] = $foreign.writeState;
  exports["readState"] = $foreign.readState;;
 
})(PS["React"] = PS["React"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module React.DOM.Props

  exports.unsafeMkProps = function(key) {
      return function(value) {
          var result = {};
          result[key] = value;
          return result;
      };
  };

  exports.unsafeUnfoldProps = function(key) {
      return function(value) {
          var result = {};
          var props = {};
          props[key] = result;

          for (var subprop in value) {
              if (value.hasOwnProperty(subprop)) {
                  result[subprop] = value[subprop];
              }
          }

          return props;
      };
  };
 
})(PS["React.DOM.Props"] = PS["React.DOM.Props"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["React.DOM.Props"];
  var React = PS["React"];
  var Prelude = PS["Prelude"];                      
  var style = $foreign.unsafeUnfoldProps("style");
  var onClick = function (f) {
      return $foreign.unsafeMkProps("onClick")(React.handle(f));
  };                                              
  var className = $foreign.unsafeMkProps("className");
  var _id = $foreign.unsafeMkProps("id");
  exports["onClick"] = onClick;
  exports["_id"] = _id;
  exports["className"] = className;
  exports["style"] = style;;
 
})(PS["React.DOM.Props"] = PS["React.DOM.Props"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var $foreign = PS["React.DOM"];
  var Prelude = PS["Prelude"];
  var React = PS["React"];
  var React_DOM_Props = PS["React.DOM.Props"];
  var p = $foreign.mkDOM("p");
  var div = $foreign.mkDOM("div");
  exports["p"] = p;
  exports["div"] = div;
  exports["text"] = $foreign.text;;
 
})(PS["React.DOM"] = PS["React.DOM"] || {});
(function(exports) {
  // Generated by psc version 0.7.0.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff_Console = PS["Control.Monad.Eff.Console"];
  var Leaflet_LatLng = PS["Leaflet.LatLng"];
  var Leaflet_LatLngBounds = PS["Leaflet.LatLngBounds"];
  var React_DOM = PS["React.DOM"];
  var React = PS["React"];
  var React_DOM_Props = PS["React.DOM.Props"];
  var DOM_HTML = PS["DOM.HTML"];
  var DOM_HTML_Window = PS["DOM.HTML.Window"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];
  var Data_Nullable = PS["Data.Nullable"];
  var DOM_HTML_Document = PS["DOM.HTML.Document"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  var Leaflet_Map = PS["Leaflet.Map"];
  var Leaflet_TileLayer = PS["Leaflet.TileLayer"];
  var Leaflet_Types = PS["Leaflet.Types"];
  var Leaflet_Icon = PS["Leaflet.Icon"];
  var Leaflet_Marker = PS["Leaflet.Marker"];
  var Debug_Trace = PS["Debug.Trace"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_String = PS["Data.String"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];     
  var mapBoxUrl = "https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6IjZjNmRjNzk3ZmE2MTcwOTEwMGY0MzU3YjUzOWFmNWZhIn0.Y8bhBaUMqFiPrDRW9hieoQ";
  var incrementCounter = function (ctx) {
      return function (e) {
          return function __do() {
              var _18 = React.readState(ctx)();
              return React.writeState(ctx)(Prelude["+"](Prelude.semiringInt)(_18)(1))();
          };
      };
  };
  var counter = React.createClass(React.spec(0)(function (ctx) {
      return function __do() {
          var _19 = React.readState(ctx)();
          return Prelude["return"](Control_Monad_Eff.applicativeEff)(React_DOM.p([ React_DOM_Props.className("Counter"), React_DOM_Props.onClick(incrementCounter(ctx)) ])([ React_DOM.text(Prelude.show(Prelude.showInt)(_19)), React_DOM.text(" Click me to increment!") ]))();
      };
  }));
  var convert_degrees_to_decimal = function (degrees) {
      return function (minutes) {
          var _491 = degrees >= 0.0;
          if (_491) {
              return degrees + minutes / 60.0;
          };
          if (!_491) {
              return degrees - minutes / 60.0;
          };
          throw new Error("Failed pattern match at /home/travis/build/lewurm/geocaching-history/front-end/src/Main.purs line 74, column 1 - line 75, column 1: " + [ _491.constructor.name ]);
      };
  };
  var main = function __do() {
      Control_Monad_Eff_Console.log("Hello sailor!")();
      var north = convert_degrees_to_decimal(37.0)(46.5);
      Control_Monad_Eff_Console.log("sup1: " + Prelude.show(Prelude.showNumber)(north))();
      var west = convert_degrees_to_decimal(-122.0)(25.5);
      Control_Monad_Eff_Console.log("sup2: " + Prelude.show(Prelude.showNumber)(west))();
      var ll = Leaflet_LatLng.latLng(north)(west);
      var lower = Leaflet_LatLng.latLng(convert_degrees_to_decimal(35.0)(42.5))(convert_degrees_to_decimal(-115.0)(23.0));
      var upper = Leaflet_LatLng.latLng(convert_degrees_to_decimal(39.0)(49.5))(convert_degrees_to_decimal(-128.0)(28.0));
      var bounds = Leaflet_LatLngBounds.latLngBounds(lower)(upper);
      var opts = {
          attributionControl: true, 
          center: ll, 
          layers: [  ], 
          maxBounds: bounds, 
          zoom: 12.0
      };
      var ui = React_DOM.div([  ])([ React.createFactory(counter)({}), React_DOM.div([ React_DOM_Props._id("map"), React_DOM_Props.style({
          width: "600px", 
          height: "400px"
      }) ])([  ]) ]);
      var container = function __do() {
          var _14 = DOM_HTML.window();
          var _13 = DOM_HTML_Window.document(_14)();
          var _12 = Prelude["<$>"](Control_Monad_Eff.functorEff)(Prelude["<$>"](Prelude.functorFn)(Data_Maybe_Unsafe.fromJust)(Data_Nullable.toMaybe))(DOM_HTML_Document.body(_13))();
          return Prelude["return"](Control_Monad_Eff.applicativeEff)(DOM_HTML_Types.htmlElementToElement(_12))();
      };
      Prelude[">>="](Control_Monad_Eff.bindEff)(container)(React.render(ui))();
      var _17 = Leaflet_Map.createMap("map")(opts)();
      var _16 = Leaflet_TileLayer.tileLayer(mapBoxUrl)({
          id: "mapbox.streets", 
          subdomains: [  ]
      })();
      Leaflet_Types.addTo(Leaflet_TileLayer.tileLayerLayer)(_16)(_17)();
      var _15 = Leaflet_Icon.icon({
          iconUrl: "http://www.geocaching.com/images/wpttypes/sm/2.gif", 
          iconSize: {
              x: 14, 
              y: 14
          }
      })();
      return Leaflet_Types.addTo(Leaflet_Marker.markerLayer)(Leaflet_Marker.marker({
          icon: _15
      })(ll))(_17)();
  };
  exports["counter"] = counter;
  exports["incrementCounter"] = incrementCounter;
  exports["convert_degrees_to_decimal"] = convert_degrees_to_decimal;
  exports["main"] = main;
  exports["mapBoxUrl"] = mapBoxUrl;;
 
})(PS["Main"] = PS["Main"] || {});

PS["Main"].main();
